version: "3"

services:
  minerbot:
    container_name: minerbot
    build: ./app
    env_file: .env
    restart: unless-stopped

  nginx:
    build: ./nginx
    restart: always
    container_name: minerbot-nginx
    env_file: .env
    environment:
      - VIRTUAL_HOST=${URL}
      - LETSENCRYPT_HOST=${URL}
      - LETSENCRYPT_EMAIL=${EMAIL_HOST_USER}
    depends_on:
      - minerbot

networks:
  default:
    external:
      name: proxy-bypass
